# Generated by Django 4.2.7 on 2023-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='biography',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
